### DISCUSSION TITLE
Does a "Too Many Requests 429. Skipping..." error mean that check-in will fail?

### DISCUSSION THREAD

**Discussion by gene1wood** [jdholtz/auto-southwest-check-in#302] [Q&A] [answered]
When I run the docker container, passing in confirmation number, first and last, and the output shows something like

```
auto-southwest    | Requesting error during fare check. Too Many Requests 429. Skipping...
auto-southwest    | Requesting error during fare check. Too Many Requests 429. Skipping...
```

Is that an ephemeral error, and when it's time to check-in for the flight it will work? Or is that an indicator that something isn't working and when check-in time comes around it will fail?

I get this with a `docker-compose.yml` that looks like this

```
services:
  auto-southwest:
    image: jdholtz/auto-southwest-check-in
    container_name: auto-southwest
    restart: on-failure
    environment:
      - AUTO_SOUTHWEST_CHECK_IN_NOTIFICATION_URL=ntfys://RECACTED/
      - AUTO_SOUTHWEST_CHECK_IN_CONFIRMATION_NUMBER=REDACTED
      - AUTO_SOUTHWEST_CHECK_IN_FIRST_NAME=REDACTED
      - AUTO_SOUTHWEST_CHECK_IN_LAST_NAME=REDACTED

```
